### ISSUE TITLE
Fonts are loaded repeatedly

### ISSUE THREAD

**Issue by byorgey** [diagrams/SVGFonts#16]
It seems that fonts are sometimes repeatedly reloaded from disk, once for each call to `textSVG` or a similar function.  See the previous discussion at https://github.com/timbod7/haskell-chart/pull/83 .

**Comment by tkvogt** [comment]
I will add a function that uses a lookup to prevent this

**Comment by byorgey** [comment]
I'm not sure I understand.  How exactly will doing a lookup prevent this?

**Comment by tkvogt** [comment]
haskell-chart already uses a [lookup](https://github.com/timbod7/haskell-chart/blob/ee4549a8260fe9804c42e16b08d4fc270b066c66/chart-diagrams/Graphics/Rendering/Chart/Backend/Diagrams.hs#L322) for custom fonts. The [default fonts](https://github.com/timbod7/haskell-chart/blob/ee4549a8260fe9804c42e16b08d4fc270b066c66/chart-diagrams/Graphics/Rendering/Chart/Backend/Diagrams.hs#L244) on the other hand have no lookup and the compiler most likely does not remember [constant assignement in a do notation](https://github.com/timbod7/haskell-chart/blob/ee4549a8260fe9804c42e16b08d4fc270b066c66/chart-diagrams/Graphics/Rendering/Chart/Backend/Diagrams.hs#L246) of a paramerterized function. To prevent a mistake like this it is convenient to add a global Hashmap that caches the Font data, although it might add little overhead.

**Comment by byorgey** [comment]
Hmm, I see. It is certainly worth trying.

**Comment by Fuuzetsu** [comment]
Hi; this is still around and makes performance honestly not acceptable in any application using `textSVG` multiple times, sadly. Is there any plan to fix it? I may give it a go shortly but if there's a patch lying around somewhere I'd rather spare myself the pain.

**Comment by Fuuzetsu** [comment]
Hm, upon testing, seems loading only happens once. Perhaps something else should be blame for poor performance now.

**Comment by byorgey** [comment]
@Fuuzetsu thanks for the nudge on this issue.  Can you be more specific about the poor performance you are seeing?  If the parser is only being called once then it should not make a difference how many times you use `textSVG`.

**Comment by Fuuzetsu** [comment]
I think there are few problems:

1. Initial load overhead is too high: if we want to render few pieces of text, it sucks that loading the font takes so long; better loading qould help here. I managed to speed up parser by third pretty trivially on a branch somewhere

2. Following up on above, memory cost seems way too high for what we're doing, we're reading 18MB file in effectively a flat format so why does it take so 100+MB resident memory to load the font? This sucks for programs where memory cost would otherwise be low.

3. Actual usage seems to cost a lot. Even for simple, short strings it takes a lot of time and memory to create a Diagram. If you have multiple strings then things get really bad. For examppe I was able to reduce memory usage and runtime by around an order of magnitude just by reducing number of times we call textSVG. I have to measure if maybe it's worth rendering 1 big string at once where possible. For comparison, using text from diagrams instead of textSVG nearly completely eliminates any runtime and memory issuea from ghc-events-anaylze whereas it qould happily take many many minutes and tens of GBs of memory even on small input.

I can maybe fix 1 and 2 reducing constant overhead but really I'm interested in 3. Honestly I just want some fast text, not even vectorised, that is sized as far as diagrams is concerned. My current hack is to take longest string from my set, textSVG and take width as an approximation for getting biggest "width". As far as addressing core problem (textSVG is slow and memory hungry), I know very little about diagrams and don't know if we can have much improvement there...

I think this issue can be closed if there are issues for above points as I managed to convince myself that only 1 load is occuring.

**Comment by byorgey** [comment]
Re: your edit, great!  I'm sure (1) and (2) could be improved.  As for (3), it may be more an issue with diagrams itself than with SVGFonts.  The diagrams `text` function creates a simple text object which uses native text support in the backend.  SVGFonts, on the other hand, creates (possibly complicated) paths.  Empirically we are talking about ~20 Bezier segments per letter.  I don't actually think diagrams should be that slow in handling paths with hundreds or thousands of segments but I am not sure.

**Comment by byorgey** [comment]
OK, I'm closing this issue for now then.  I've opened #22 as a placeholder for further performance improvements.
